### ISSUE TITLE
项目介绍处有点建议

### ISSUE THREAD

**Issue by dubiao** [zelda/Resume#1]
![wechatimg138](https://cloud.githubusercontent.com/assets/4001793/23841636/a45068b4-07e9-11e7-9f71-3054ea7abdb8.jpeg)
三个红线的地方是不是应该换行？

**Comment by shiiiiiiji** [comment]
我试试看看换行会不会好看点，之前是Word版本的简历描述，就直接搬上来了

**Comment by shiiiiiiji** [comment]
多谢反馈
